export default {
  JUMP_TO_TIMELINE: "JUMP_TO_TIME_LINE",
  JUMP_TO_COLLABORATION: "JUMP_TO_COLLABORATION",
  JUMP_TO_SIMILARITY: "JUMP_TO_SIMILARITY",
  SET_SONG: "SET_SONG",
  SET_ARTIST: "SET_ARTIST",
  PAUSE_ALL_YOUTUBE: "PAUSE_ALL_YOUTUBE"
};
