export default {
  JUMP_TO_TIMELINE: "JUMP_TO_TIME_LINE",
  JUMP_TO_COLLABORATION: "JUMP_TO_COLLABORATION",
  JUMP_TO_SIMILARITY: "JUMP_TO_SIMILARITY",
  SET_SIMILARITY_SONG: "SET_SIMILARITY_SONG",
  SET_ARTIST: "SET_ARTIST",
  SET_TIMELINE_SONG: "SET_TIMELINE_SONG",
  PAUSE_ALL_YOUTUBE: "PAUSE_ALL_YOUTUBE",
  OPEN_GENRES_MODAL: "OPEN_GENRES_MODAL",
};
